CREATE DIRECTORY DOCKER_FILES AS '/tmp/docker-files';

CREATE TABLESPACE "TBS_DDGP" DATAFILE 
'/u01/app/oracle/oradata/XE/tbs_ddgp.dbf' SIZE 10485760
AUTOEXTEND ON NEXT 10485760 MAXSIZE 11264M
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "TBS_PDGP" DATAFILE 
'/u01/app/oracle/oradata/XE/tbs_pdgp.dbf' SIZE 10485760
AUTOEXTEND ON NEXT 10485760 MAXSIZE 11264M
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

CREATE PUBLIC DATABASE LINK TO_RDS_BREPORTS CONNECT TO BREPORTS_LINK IDENTIFIED BY L0m4aV
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=pdgdb.cy8ep9k6o8za.sa-east-1.rds.amazonaws.com)(PORT=1521))(CONNECT_DATA=(SID=pdgdb)))';

CREATE PUBLIC SYNONYM BREPORTS_GERALINK FOR BREPORTS_GERALINK@TO_RDS_BREPORTS;