DECLARE
  vGOAL_VERSION             NUMBER;
BEGIN
  vGOAL_VERSION := 31;

--  STARTUP UPGRADE;
	EXECUTE IMMEDIATE ('PURGE DBA_RECYCLEBIN');
	EXECUTE IMMEDIATE ('TRUNCATE TABLE SYS.DST$TRIGGER_TABLE');
	EXECUTE IMMEDIATE ('TRUNCATE TABLE SYS.DST$AFFECTED_TABLES');
	EXECUTE IMMEDIATE ('TRUNCATE TABLE SYS.DST$ERROR_TABLE');
  --DBMS_APPLICATION_INFO.SET_CLIENT_INFO('UPG_TZV')

	EXECUTE IMMEDIATE ('ALTER SESSION SET "_WITH_SUBQUERY"=MATERIALIZE');
	EXECUTE IMMEDIATE ('ALTER SESSION SET "_SIMPLE_VIEW_MERGING"=TRUE');

  DBMS_DST.BEGIN_UPGRADE(vGOAL_VERSION);

/*
  SELECT * FROM sys.dst$error_table;

  SELECT PROPERTY_NAME, SUBSTR(PROPERTY_VALUE, 1, 30) VALUE
  FROM DATABASE_PROPERTIES
  WHERE PROPERTY_NAME LIKE 'DST_%'
  ORDER BY PROPERTY_NAME;

PROPERTY_NAME              VALUE
-------------------------  ------------------------------------
DST_PRIMARY_TT_VERSION     26
DST_SECONDARY_TT_VERSION   18
DST_UPGRADE_STATE          UPGRADE
— some oracle provided users may be listed here, that is normal

SQL> SELECT OWNER, TABLE_NAME, UPGRADE_IN_PROGRESS
FROM ALL_TSTZ_TABLES
where UPGRADE_IN_PROGRESS='YES';
*/
	
END;	 
/